version: "3.6"

networks:
  rust_api:
    name: rust_api

services:
  rust_api_db:
    image: postgres
    container_name: rust_api_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      rust_api:
        aliases:
          - rust_api_db

  adminer:
    image: adminer
    container_name: rust_api_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rust_api_db
    networks:
      rust_api:
        aliases:
          - rust_api_adminer

  # rust_api_server:
  #   build: 
  #     context: ./.docker/api_server
  #     dockerfile: Dockerfile
  #     args:
  #       - database_url=${DATABASE_URL}
  #   container_name: rust_api_server
  #   restart: always
  #   depends_on:
  #     - rust_api_db
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./:/api_server/
  #   env_file: 
  #     - .env
  #   networks:
  #     rust_api:
  #       aliases:
  #         - rust_api_server