version: "3.6"

networks:
  rust_api:
    name: rust_api

services:
  rust_api_server:
    build: ./.docker/api_server
    container_name: rust_api_server
    restart: always
    ports:
      - 8000:8000
    depends_on:
      pg_db:
        condition: service_healthy
    volumes:
      - ./:/api_server/
    env_file: 
      - .env
    command: bash -c "diesel setup && cargo watch -x run"
    networks:
      rust_api:
        aliases:
          - rust_api_server

  adminer:
    image: adminer
    container_name: rust_api_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      pg_db:
        condition: service_healthy
    networks:
      rust_api:
        aliases:
          - rust_api_adminer
  
  pg_db:
    image: postgres
    ports:
      - 5432:5432
    container_name: pg_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rust_api_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      rust_api:
        aliases:
          - pg_db

volumes:
  pgdata: {}